micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - '*'
        exposedHeaders:
          - Content-Type
          - Authorization
          - '*'
#  security:
#    authentication: bearer
#    token:
#      jwt:
#        signatures:
#          secret:
#            generator:
#              refresh-token:
#                secret: thisisthekey
  application:
    name: todoApp
---
#tag::datasource[]
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/todo
    username: user
    password: password
    driverClassName: org.postgresql.Driver
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true

