micronaut:
  application:
    name: todoApp

datasources:
  default: 
  url: jdbc:postgresql://localhost:5432/todo
  driverClassNmae: org.postgresql.Driver
  username: user
  password: password
  schema-generate: CREATE_DROP
  dialect: POSTGRES
  jpa.default.properties.hibernate.hbm2ddl.auto: update
